server:
  port: 3001
  sessionSecret: secret
  lti:
    roomMapUrl:
    redisUrl:
    consumerKey: key
    consumerSecret: secret
  
client:
  dataServer:
    path:
    email: default-user-email
    password: default-user-password
  faceTracking:
    enabled: false
    overlay: false
    eventFrequency: 500
