client:
  react_app_debug: true
  webrtc_debug: true
  # the docker container reverse proxy will forward websocket connections
  signalMaster:
    url: /

  # the docker container reverse proxy will forward REST and websocket connections
  dataServer:
    url: /
    path: /api/videodata
